### ISSUE TITLE
Bilder zu Produkten werden ab und zu mit der falschen Produkt-Id 0 gespeichert

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#198]
[PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'
Request URL: /admin/products/saveUploadedImageProduct
Stack Trace:
#0 /foodcoopshop/Vendor/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php(472): PDOStatement->execute(Array)
#1 /foodcoopshop/Vendor/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php(438): DboSource->_execute('INSERT INTO `d0...', Array)
#2 /foodcoopshop/Vendor/cakephp/cakephp/lib/Cake/Model/Datasource/DboSource.php(1092): DboSource->execute('INSERT INTO `d0...')
#3 /foodcoopshop/Vendor/cakephp/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create(Object(Image), Array, Array)
#4 /foodcoopshop/Vendor/cakephp/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave(Array, Array)
#5 /foodcoopshop/Plugin/Admin/Controller/ProductsController.php(175): Model->save(Array)
#6 [internal function]: ProductsController->saveUploadedImageProduct()
#7 /foodcoopshop/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ProductsController), Array)
#8 /foodcoopshop/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /foodcoopshop/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ProductsController), Object(CakeRequest))
#10 /foodcoopshop/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}

**Comment by mrothauer** [comment]
fixed with commit https://github.com/foodcoopshop/foodcoopshop/commit/da10e8ac46ac4b38c92d4bb76bb85a0122ae7f41
